### ISSUE TITLE
Hardware version problem

### ISSUE THREAD

**Issue by nervewax** [leon-anavi/rpi-nodejs-examples#2]
Hi Leon, thanks for providing this tutorial, really useful.

I've hit this error when running the js, which I think is related to the version of wiring-pi? I get the same error when I run `gpio -v`.

```
Unable to determine hardware version. I see: Hardware   : BCM2835
,
 - expecting BCM2708 or BCM2709. Please report this to projects@drogon.net
```

Is there a fix for this that you know of?
I also noticed someone else [reported the same error](https://www.raspberrypi.org/forums/viewtopic.php?t=182191) earlier last year.

Edit: Looks like the issue is with the wiringpi version that's used in the node repo: https://github.com/WiringPi/WiringPi-Node/issues/88

**Comment by leon-anavi** [comment]
Hi, 

Hm, yes, this seems as a problem of the underlying library on which my examples rely. What kind of Raspberry Pi are you using?

Best regards,
Leon

**Comment by deanrad** [comment]
I get this now with a PI 3..

**Comment by leon-anavi** [comment]
Hi @deanius,

It is a bug caused by the underling library [wiring-pi](https://www.npmjs.com/package/wiring-pi) which unfortunately is no longer maintained. Sorry for the bad news. You can have a look at my other examples at: https://github.com/leon-anavi/iot-javascript-rpi

Best regards, Leon
